.TH "includes/attributs.h" 3 "Dimanche 17 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/attributs.h \- Fichier regroupant les attributs en commun des entités\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBvx\fP"
.br
.ti -1c
.RI "float \fBvy\fP"
.br
.ti -1c
.RI "\fBtypeEntite\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBestMort\fP"
.br
.ti -1c
.RI "int \fBnb_lancer\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Fichier regroupant les attributs en commun des entités\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020
.RE
.PP
Ce fichier est utilisé afin d'éviter la redondance de déclarations\&. 
.SH "Documentation des variables"
.PP 
.SS "\fBbool\fP estMort"
un type booleen pour savoir c'est l'entite est mort> 
.SS "float h"
hauteur de l'entite 
.br
 
.SS "int nb_lancer"
un compteur pour savoir le nb de lancer, attaque en cours> 
.br
 
.SS "\fBtypeEntite\fP type"
le type de l'entite 
.br
 
.SS "float vx"
la velocite x la vitesse laquelle va l'entite dans une direction x 
.SS "float vy"
la velocite y , la vitesse laquelle va l'entite dans une direction y 
.br
 
.SS "float w"
largeur de l'entite 
.br
 
.SS "float x"
la position x 
.br
 
.SS "float y"
la position y 
.br
 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
