.TH "includes/baseGame.h" 3 "Samedi 16 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/baseGame.h \- Programme qui gère les menus principal du jeu\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'constantes\&.h'\fP
.br
\fC#include 'game_objects\&.h'\fP
.br
\fC#include 'entite\&.h'\fP
.br
\fC#include 'player\&.h'\fP
.br
\fC#include 'level\&.h'\fP
.br
\fC#include 'liste_elements\&.h'\fP
.br
\fC#include 'charge_save\&.h'\fP
.br
\fC#include 'texture\&.h'\fP
.br
\fC#include 'hud\&.h'\fP
.br
\fC#include 'inventaire\&.h'\fP
.br
\fC#include 'menu_principal\&.h'\fP
.br
\fC#include 'menu_load\&.h'\fP
.br
\fC#include 'menu_pause\&.h'\fP
.br
\fC#include 'menu_win\&.h'\fP
.br
\fC#include 'menu_continue\&.h'\fP
.br
\fC#include 'menu_help\&.h'\fP
.br
\fC#include 'interface\&.h'\fP
.br
\fC#include 'game_over\&.h'\fP
.br
\fC#include 'definitions\&.h'\fP
.br

.SS "Structures de données"

.in +1c
.ti -1c
.RI "struct \fBbasegame\fP"
.br
.RI "Structure principale de jeux, qui gère tous les composants du jeux majeurs\&. "
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBbasegame\fP \fBBase_Game\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère les menus principal du jeu\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBbasegame\fP \fBBase_Game\fP"
This is the documentation for the preceding typedef 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
