.TH "src/baseGame.c" 3 "Vendredi 6 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/baseGame.c \- Programme qui gère les différents comportements du jeu en fonction de l'état\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br
\fC#include 'commun\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBBase_Game\fP * \fBgetBaseGame\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP (float dt)"
.br
.ti -1c
.RI "void \fBRendu_Jeux\fP ()"
.br
.ti -1c
.RI "void \fBUpdate_Listes\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBase_Game\fP \fBgame\fP"
.br
.ti -1c
.RI "int \fBlast_frame_time\fP = 0"
.br
.ti -1c
.RI "float \fBdt\fP = 0\&.0f"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère les différents comportements du jeu en fonction de l'état\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
