.TH "src/chargeSave.c" 3 "Vendredi 6 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/chargeSave.c \- Programme qui gère le chargement et la sauvegarde des parties\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'chargeSave\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBChargerPartie\fP ()"
.br
.ti -1c
.RI "void \fBSauvegarderPartie\fP ()"
.br
.ti -1c
.RI "void \fBSaveCollider_Position\fP ()"
.br
.ti -1c
.RI "void \fBChargementCollider\fP (const char *filename)"
.br
.ti -1c
.RI "void \fBChargement_CreationPNJ\fP (\fBLinkedList\fP *lst, char *filename)"
.br
.ti -1c
.RI "void \fBChargementItems\fP (const char *filename, SDL_Texture *tex)"
.br
.ti -1c
.RI "void \fBChargementEnnemis\fP (const char *filename)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le chargement et la sauvegarde des parties\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
