.TH "includes/commun.h" 3 "Mardi 19 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/commun.h \- Programme qui a les enumerations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_image\&.h>\fP
.br
\fC#include <SDL2/SDL_ttf\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <SDL2/SDL_mixer\&.h>\fP
.br

.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBbool\fP { \fBfalse\fP, \fBtrue\fP }"
.br
.RI "énumération représentant un type booléen\&. "
.ti -1c
.RI "enum \fBtypeEntite\fP { \fBitem\fP, \fBjoueur\fP, \fBennemi\fP, \fBplatform\fP, \fBcheckpoint\fP, \fBbull\fP, \fBfeu\fP, \fBos\fP, \fBrock\fP, \fBtree\fP, \fBgamewin\fP, \fBpassport\fP }"
.br
.RI "énumération représentant les types du jeux\&. "
.ti -1c
.RI "enum \fBtexState\fP { \fBfixe\fP, \fBanime\fP }"
.br
.RI "énumération les états d'une entité: fixe ou animé "
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "SDL_Renderer * \fBgetRenderer\fP (void)"
.br
.RI "Fonction qui permet d'accéder à la structure du rendu\&. "
.in -1c
.SH "Description détaillée"
.PP 
Programme qui a les enumerations\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "SDL_Renderer* getRenderer (void)"

.PP
Fonction qui permet d'accéder à la structure du rendu\&. Accès à la structure d'un rendu
.PP
\fBRenvoie\fP
.RS 4
un pointeur sur une structure de type SDL_Renderer 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
