.TH "includes/constantes.h" 3 "Dimanche 17 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/constantes.h \- Programme qui gère les constantes du tout le jeu, notamment les dimensions du niveau, dimensions de la fenetre et le menu pricipal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONSTANTS_H\fP"
.br
.RI "Clause de mise en garde pour le fichier CONSTANTS_H\&. "
.ti -1c
.RI "#define \fBGRAVITY\fP   0\&.35f"
.br
.RI "Gravite applique dans le jeu\&. "
.ti -1c
.RI "#define \fBFPS\fP   60"
.br
.RI "Nombres d'images par seconde à l'écran\&. "
.ti -1c
.RI "#define \fBFRAME_TARGET_TIME\fP   (1000/\fBFPS\fP)"
.br
.RI "Nombre d'images affichable à l'écran par seconde que l'on cherche à obtenir\&. "
.ti -1c
.RI "#define \fBLARGEUR_NIVEAU\fP   9000"
.br
.RI "LARGEUR NIVEAU\&. "
.ti -1c
.RI "#define \fBHAUTEUR_NIVEAU\fP   720"
.br
.RI "HAUTEUR NIVEAU\&. "
.ti -1c
.RI "#define \fBLARGEUR_FENETRE\fP   1280"
.br
.RI "LARGEUR FENETRE\&. "
.ti -1c
.RI "#define \fBHAUTEUR_FENETRE\fP   720"
.br
.RI "HAUTEUR FENETRE\&. "
.ti -1c
.RI "#define \fBMENU_PRINCIPAL\fP   0"
.br
.RI "MENU PRINCIPAL\&. "
.ti -1c
.RI "#define \fBIN_GAME\fP   1"
.br
.RI "PARTIE EN COURS\&. "
.ti -1c
.RI "#define \fBPAUSE\fP   3"
.br
.RI "JEU EN PAUSE\&. "
.ti -1c
.RI "#define \fBgame_over\fP   4"
.br
.RI "GAME OVER\&. "
.ti -1c
.RI "#define \fBLEVEL_COMPLETED\fP   5"
.br
.RI "NIVEAU TERMINE\&. "
.ti -1c
.RI "#define \fBLOADING\fP   6"
.br
.RI "PAGE DE CHARGEMENT\&. "
.ti -1c
.RI "#define \fBINVENTAIRE\fP   7"
.br
.RI "MENU INVENTAIRE\&. "
.ti -1c
.RI "#define \fBGAMEWIN\fP   8"
.br
.RI "PARTIE GAGNE\&. "
.ti -1c
.RI "#define \fBHELP\fP   9"
.br
.RI "AIDE 
.br
 "
.ti -1c
.RI "#define \fBNOUVELLE_PARTIE\fP   0"
.br
.RI "MENU PRINCIPAL\&. "
.ti -1c
.RI "#define \fBCHARGER_PARTIE\fP   1"
.br
.RI "Charger une partie\&. "
.ti -1c
.RI "#define \fBQUITTER_PARTIE\fP   2"
.br
.RI "Quitter une partie\&. "
.ti -1c
.RI "#define \fBNIVEAU1\fP   1"
.br
.RI "PREMIER NIVEAU\&. "
.ti -1c
.RI "#define \fBNIVEAU2\fP   2"
.br
.RI "DEUXIEME NIVEAU\&. "
.ti -1c
.RI "#define \fBMAX_ITEMS\fP   3"
.br
.RI "Nombre maximum d'items\&. "
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère les constantes du tout le jeu, notamment les dimensions du niveau, dimensions de la fenetre et le menu pricipal\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des macros"
.PP 
.SS "#define NOUVELLE_PARTIE   0"

.PP
MENU PRINCIPAL\&. Lancer une nouvelle partie 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
