.TH "includes/enjeu.h" 3 "Dimanche 17 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/enjeu.h \- Programme fait appel a la fonction input qui gere le clavier quand on est dans le jeu\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'commun\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__INGAME_H\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBInput_InGame\fP (SDL_Event *event)"
.br
.RI "Fonction qui permet gérer les entr"es clavier et la camera lorsqu'une partie est en cours\&. "
.in -1c
.SH "Description détaillée"
.PP 
Programme fait appel a la fonction input qui gere le clavier quand on est dans le jeu\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des macros"
.PP 
.SS "#define __INGAME_H"
__INGAME_H 
.SH "Documentation des fonctions"
.PP 
.SS "void Input_InGame (SDL_Event * event)"

.PP
Fonction qui permet gérer les entr"es clavier et la camera lorsqu'une partie est en cours\&. Gestion entrées clavier et caméra
.PP
Gestion des entrées de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP pointeur sur une structure SDL evenement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
