.TH "src/enjeu.c" 3 "Vendredi 6 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/enjeu.c \- Programme qui gère les entrées utilisateur (touches) et la caméra\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'enjeu\&.h'\fP
.br
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBInput_InGame\fP (SDL_Event *event)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SDL_Rect \fBcamera\fP = {0,0,LARGEUR_FENETRE, HAUTEUR_FENETRE}"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère les entrées utilisateur (touches) et la caméra\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
