.TH "includes/entity.h" 3 "Mercredi 5 Février 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/entity.h \- Fichier d'en-tête pour la définition du type Entité  

.SH SYNOPSIS
.br
.PP
\fC#include 'commun\&.h'\fP
.br

.SS "Structures de données"

.in +1c
.ti -1c
.RI "struct \fBEntity\fP"
.br
.RI "Structure de base réprésentant les entités vivantes du jeux\&. "
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBEntity\fP \fBEntity_t\fP"
.br
.RI "typedef pour la structure \fBEntity\fP "
.in -1c
.SH "Description détaillée"
.PP 
Fichier d'en-tête pour la définition du type Entité 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
