.TH "src/entite.c" 3 "Samedi 2 Mai 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/entite.c \- Programme qui gère le comportement des entités\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBUpdateBullets\fP (\fBtypeEntite\fP typeA, \fBtypeEntite\fP typeB)"
.br
.RI "Fonction qui permet mettre a jour les bullets\&. "
.ti -1c
.RI "void \fBSetNombreTir_Ennemis\fP ()"
.br
.RI "Fonction qui configurer le nombre de tir des ennemis\&. "
.ti -1c
.RI "void \fBCreerTir\fP (\fBtypeEntite\fP type, int width, int height, int startX, int startY)"
.br
.RI "Fonction qui creer un tir\&. "
.ti -1c
.RI "void \fBattaqueEnnemis\fP ()"
.br
.RI "Fonction qui gère les attaques des ennemis\&. "
.ti -1c
.RI "void \fBUpdateEnnemis\fP ()"
.br
.RI "Fonction qui met a jour les ennemis\&. "
.ti -1c
.RI "void \fBcollisionDetection\fP ()"
.br
.RI "Fonction qui gere les collision entre le joueur et le decor, le joueur et les ennemis; et si le joueur tombe dans le vide\&. "
.ti -1c
.RI "void \fBcollision_Decor\fP ()"
.br
.RI "Fonction qui gere les collisions avec le decor\&. "
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le comportement des entités\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020
.RE
.PP
Gestion des collisions entre le joueur et le décor (plateformes), le joueur et les ennemis, les ennemis et les projectiles ou si le joueur tombe dans le vide 
.SH "Documentation des fonctions"
.PP 
.SS "void attaqueEnnemis ()"

.PP
Fonction qui gère les attaques des ennemis\&. Parcours des ennemis, verification qu'il n'est pas mort et de son compteur de lancer 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void collision_Decor ()"

.PP
Fonction qui gere les collisions avec le decor\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void collisionDetection ()"

.PP
Fonction qui gere les collision entre le joueur et le decor, le joueur et les ennemis; et si le joueur tombe dans le vide\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void CreerTir (\fBtypeEntite\fP type, int width, int height, int startX, int startY)"

.PP
Fonction qui creer un tir\&. 
.PP
\fBParamètres\fP
.RS 4
\fItype\fP type du tir 
.br
\fIwidth\fP largeur du sprite 
.br
\fIheight\fP hauteur du sprite 
.br
\fIstartX\fP position en x du sprite 
.br
\fIstartY\fP position en y du sprite 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void SetNombreTir_Ennemis ()"

.PP
Fonction qui configurer le nombre de tir des ennemis\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "\fBbool\fP UpdateBullets (\fBtypeEntite\fP typeA, \fBtypeEntite\fP typeB)"

.PP
Fonction qui permet mettre a jour les bullets\&. Parcours de la listes des bullets
.PP
En fonction de si il s'agit d'un ennemi ou du joueur, le comportement des bullets est différent 
.PP
\fBParamètres\fP
.RS 4
\fItypeA\fP type de la premiere entite : item, joueur, ennemi, platform , bull, feu 
.br
\fItypeB\fP type de la deuxieme entite : item, joueur, ennemi, platform , bull, feu 
.RE
.PP
\fBRenvoie\fP
.RS 4
Une valeur de type booleen 
.RE
.PP

.SS "void UpdateEnnemis ()"

.PP
Fonction qui met a jour les ennemis\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
