.TH "src/gameOver.c" 3 "Lundi 4 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gameOver.c \- Programme qui gère le menu du game over\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBMenu_t\fP * \fBgetMenu_Over\fP ()"
.br
.RI "Fonction qui permet de retourner le menu du game over\&. "
.ti -1c
.RI "void \fBInit_MenuGameOver\fP ()"
.br
.RI "Fonction qui initialise le menu game over\&. "
.ti -1c
.RI "void \fBInput_MenuGameOver\fP (SDL_Event *event)"
.br
.RI "Fonction qui gère les évènements du menu\&. "
.ti -1c
.RI "void \fBInit_GameOver\fP ()"
.br
.RI "Fonction qui initialise l'état game over\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMenu_t\fP \fBmenu_over\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le menu du game over\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020
.RE
.PP
Initialisation, affichage du menu, navigation dans le menu, gestion des entrees clavier et destruction du menu 
.SH "Documentation des fonctions"
.PP 
.SS "\fBMenu_t\fP * getMenu_Over ()"

.PP
Fonction qui permet de retourner le menu du game over\&. 
.PP
\fBRenvoie\fP
.RS 4
une structure menu de type Menu_t 
.RE
.PP

.SS "void Init_GameOver ()"

.PP
Fonction qui initialise l'état game over\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Init_MenuGameOver ()"

.PP
Fonction qui initialise le menu game over\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Input_MenuGameOver (SDL_Event * event)"

.PP
Fonction qui gère les évènements du menu\&. Gestion des entrées clavier de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP évènement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Documentation des variables"
.PP 
.SS "\fBMenu_t\fP menu_over"
Structure de type menu_t 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
