.TH "includes/game_objects.h" 3 "Dimanche 17 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/game_objects.h \- programme qui gère les objets  

.SH SYNOPSIS
.br
.PP
\fC#include 'texture\&.h'\fP
.br

.SS "Structures de données"

.in +1c
.ti -1c
.RI "struct \fBcomponent\fP"
.br
.RI "Structure gérant les caractéristiques liées à un component\&. "
.ti -1c
.RI "struct \fBgameObject\fP"
.br
.RI "Structure permettant de gérer un GameObject\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_NUMBER\fP   3"
.br
.RI "Nombre maximum d'options disponibles dans un menu\&. "
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBcomponent\fP \fBComponent\fP"
.br
.ti -1c
.RI "typedef struct \fBgameObject\fP \fBGameObject\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBUpdateComponent\fP (\fBComponent\fP *\fBcomponent\fP, int etat)"
.br
.ti -1c
.RI "void \fBUpdateImage_Component\fP (\fBComponent\fP *\fBcomponent\fP, const char *filename)"
.br
.ti -1c
.RI "int \fBGetKeypressed\fP (\fBGameObject\fP *\fBgameObject\fP)"
.br
.RI "Fonction qui retourne l'option du menu selectionne\&. "
.ti -1c
.RI "void \fBGameObject_LoadRessources\fP (int numero, int num_image, \fBGameObject\fP *\fBgameObject\fP, char *image_on, char *image_off, int positionX, int positionY)"
.br
.RI "Fonction qui gere le chargement des donnes du menu\&. "
.ti -1c
.RI "void \fBUP_Key\fP (\fBGameObject\fP *\fBgameObject\fP)"
.br
.RI "Fonction qui permet de naviguer dans le menu vers le haut\&. "
.ti -1c
.RI "void \fBDOWN_Key\fP (\fBGameObject\fP *\fBgameObject\fP)"
.br
.RI "Fonction qui permet de naviguer dans le menu vers le bas\&. "
.ti -1c
.RI "void \fBRIGHT_Key\fP (\fBGameObject\fP *\fBgameObject\fP, int nombreOptions)"
.br
.RI "Fonction qui permet de naviguer dans le menu a RIGHT_Key\&. "
.ti -1c
.RI "void \fBLEFT_Key\fP (\fBGameObject\fP *\fBgameObject\fP, int nombreOptions)"
.br
.RI "Fonction qui permet de naviguer dans le menu a LEFT_Key\&. "
.ti -1c
.RI "void \fBGameObject_Render\fP (\fBGameObject\fP *\fBgameObject\fP, int nombresOptions, int posX, int posY, int largeurBG, int hauteurBG)"
.br
.RI "Fonction qui permet d'afficher le menu\&. "
.ti -1c
.RI "void \fBGameObject_Clean\fP (\fBGameObject\fP *\fBgameObject\fP, int nombreOptions)"
.br
.RI "Fonction qui permet de nettoyer l'ecran du menu\&. "
.in -1c
.SH "Description détaillée"
.PP 
programme qui gère les objets 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBcomponent\fP \fBComponent\fP"
Typedef component Component 
.SS "typedef struct \fBgameObject\fP \fBGameObject\fP"
Typedef \fBgameObject\fP GameObject 
.SH "Documentation des fonctions"
.PP 
.SS "void DOWN_Key (\fBGameObject\fP * gameObject)"

.PP
Fonction qui permet de naviguer dans le menu vers le bas\&. touche bas 
.br
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void GameObject_Clean (\fBGameObject\fP * gameObject, int nombreComponents)"

.PP
Fonction qui permet de nettoyer l'ecran du menu\&. fonction servant à libérer les ressources d'un \fBgameObject\fP
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fInombreComponents\fP nombre de components(options) du menu 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void GameObject_LoadRessources (int numero, int num_image, \fBGameObject\fP * gameObject, char * image_on, char * image_off, int positionX, int positionY)"

.PP
Fonction qui gere le chargement des donnes du menu\&. rechargement du \fBgameObject\fP
.PP
\fBParamètres\fP
.RS 4
\fInumero\fP numero de l'option 
.br
\fInum_image\fP numero de l'image selectionne par defaut 
.br
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fIimage_on\fP chemin pour acceder a l'image selectionnee 
.br
\fIimage_off\fP chemin pour acceder a l'image deselectionnee 
.br
\fIpositionX\fP position en x 
.br
\fIpositionY\fP position en y 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void GameObject_Render (\fBGameObject\fP * gameObject, int nombresOptions, int posX, int posY, int largeurBG, int hauteurBG)"

.PP
Fonction qui permet d'afficher le menu\&. Affichage des différentes options 
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fInombresOptions\fP nombre d'options dans le menu 
.br
\fIposX\fP position en x de l'arriere plan 
.br
\fIposY\fP position en y de l'arriere plan 
.br
\fIlargeurBG\fP largeur de l'arriere plan 
.br
\fIhauteurBG\fP hauteur de l'arriere plan 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "int GetKeypressed (\fBGameObject\fP * gameObject)"

.PP
Fonction qui retourne l'option du menu selectionne\&. fonction sur les touches du \fBgameObject\fP
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.RE
.PP
\fBRenvoie\fP
.RS 4
un entier correspondant au numero de l'option selectionnee 
.RE
.PP

.SS "void LEFT_Key (\fBGameObject\fP * gameObject, int nombresOptions)"

.PP
Fonction qui permet de naviguer dans le menu a LEFT_Key\&. pour aller a Gauche
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fInombresOptions\fP nombre d'options 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void RIGHT_Key (\fBGameObject\fP * gameObject, int nombresOptions)"

.PP
Fonction qui permet de naviguer dans le menu a RIGHT_Key\&. pour aller a Droite
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP Pointeur sur le \fBgameObject\fP 
.br
\fInombresOptions\fP Nombre de components utilisés 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void UP_Key (\fBGameObject\fP * gameObject)"

.PP
Fonction qui permet de naviguer dans le menu vers le haut\&. fonction pour la touche haut du \fBgameObject\fP
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void UpdateComponent (\fBComponent\fP * component, int etat)"
fonction de mise à jour du component d'un \fBgameObject\fP 
.SS "void UpdateImage_Component (\fBComponent\fP * component, const char * filename)"
fonction de mise à jour d'image du component d'un \fBgameObject\fP 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
