.TH "src/hud.c" 3 "Mercredi 18 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hud.c \- Programme qui gère le compteur de temps, le compteur de vie et le score à afficher\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBInit_HUD\fP (\fBHUD\fP *hud, const char *text, int x, int y)"
.br
.ti -1c
.RI "void \fBSetHUD_IntToTexture\fP (\fBHUD\fP *hud, const char *nom, int scores)"
.br
.ti -1c
.RI "void \fBAfficherScores\fP (\fBHUD\fP *hud)"
.br
.ti -1c
.RI "void \fBNettoyerHUD\fP (\fBHUD\fP *hud)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le compteur de temps, le compteur de vie et le score à afficher\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020
.RE
.PP
Affichage et mise à jour graphique des éléments 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
