.TH "src/hud.c" 3 "Samedi 16 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hud.c \- Programme qui gère le compteur de temps, le compteur de vie et le score à afficher\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'basegame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBInit_HUD\fP (\fBHUD\fP *hud, SDL_Color color, const char *text, int \fBx\fP, int \fBy\fP)"
.br
.RI "Fonction qui permet d'initialiser un hud\&. "
.ti -1c
.RI "void \fBSetHUD_IntToTexture\fP (\fBHUD\fP *hud, SDL_Color color, const char *nom, int valeur, int posX, int posY)"
.br
.RI "Fonction qui permet de creer la texture d'un hud\&. "
.ti -1c
.RI "void \fBRender_HUD\fP (\fBHUD\fP *hud)"
.br
.RI "Fonction qui permet d'afficher un hud\&. "
.ti -1c
.RI "void \fBClean_HUD\fP (\fBHUD\fP *hud)"
.br
.RI "Fonction qui detruit un hud\&. "
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le compteur de temps, le compteur de vie et le score à afficher\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020
.RE
.PP
Affichage et mise à jour graphique des éléments 
.SH "Documentation des fonctions"
.PP 
.SS "void Clean_HUD (\fBHUD\fP * hud)"

.PP
Fonction qui detruit un hud\&. 
.PP
\fBParamètres\fP
.RS 4
\fIhud\fP pointeur sur le hud à supprimer 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Init_HUD (\fBHUD\fP * hud, SDL_Color color, const char * text, int x, int y)"

.PP
Fonction qui permet d'initialiser un hud\&. Un hud correspond à toutes les informations concernant le joueur tels que le score ou le nombre de vie par exemple 
.PP
\fBParamètres\fP
.RS 4
\fIhud\fP pointeur sur une structure de type HUD 
.br
\fIcolor\fP enumération SDL_Color correspondant à la couleur de la police 
.br
\fItext\fP chaîne de caractère qui correspond au nom de la texture 
.br
\fIx\fP position en x du hud 
.br
\fIy\fP position en y du hud 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Render_HUD (\fBHUD\fP * hud)"

.PP
Fonction qui permet d'afficher un hud\&. 
.PP
\fBParamètres\fP
.RS 4
\fIhud\fP pointeur sur le hud à afficher 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void SetHUD_IntToTexture (\fBHUD\fP * hud, SDL_Color color, const char * nom, int valeur, int posX, int posY)"

.PP
Fonction qui permet de creer la texture d'un hud\&. 
.PP
\fBParamètres\fP
.RS 4
\fIhud\fP pointeur sur une structure de type HUD 
.br
\fIcolor\fP enumération SDL_Color correspondant à la couleur de la police 
.br
\fInom\fP chaîne de caractère de ce qu'on veut afficher 
.br
\fIvaleur\fP valeur numérique à afficher dans le hud 
.br
\fIposX\fP position en x du hud 
.br
\fIposY\fP position en y du hud 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
