.TH "hud_s" 3 "Mercredi 8 Avril 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hud_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hud\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "TTF_Font * \fBpolice\fP"
.br
.ti -1c
.RI "SDL_Surface * \fBsurface\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBtex\fP"
.br
.ti -1c
.RI "SDL_Rect \fBrect\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
structure gerant les informations concernant le joueur 
.SH "Documentation des champs"
.PP 
.SS "TTF_Font* police"
la police qui est utilise pour l'affichage du hud 
.SS "SDL_Rect rect"
le rectangle ou sera afficher le rendu du hud 
.SS "SDL_Surface* surface"
la surface qui sera convertit en texture 
.SS "SDL_Texture* tex"
correspond a la texture du hud,c'est a dire ce qui sera affiché 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
