.TH "src/inits.c" 3 "Jeudi 2 Avril 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/inits.c \- Programme qui gère les initialisations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'commun\&.h'\fP
.br
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "SDL_Renderer * \fBgetRenderer\fP (void)"
.br
.RI "Fonction qui permet d'acceder a la structure du rendu\&. "
.ti -1c
.RI "void \fBInit\fP (const char *title)"
.br
.RI "Fonction qui permet d'initialiser\&. "
.ti -1c
.RI "void \fBLibererRessources_Jeux\fP (void)"
.br
.RI "Fonction qui libere toutes les ressources du jeu\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SDL_Renderer * \fBrendu\fP = NULL"
.br
.ti -1c
.RI "SDL_Window * \fBfenetre\fP = NULL"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère les initialisations\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020
.RE
.PP
Initialisation de la fenêtre, du rendu, du son, du menu principal, du score et du joueur
.PP
Destruction du son, des ennemis, de la fenêtre, du menu prinicpal, du rendu\&.\&.\&. 
.SH "Documentation des fonctions"
.PP 
.SS "SDL_Renderer * getRenderer (void)"

.PP
Fonction qui permet d'acceder a la structure du rendu\&. 
.PP
\fBRenvoie\fP
.RS 4
un pointeur sur une structure de type SDL_Renderer 
.RE
.PP

.SS "void Init (const char * title)"

.PP
Fonction qui permet d'initialiser\&. Creation de la fenetre
.PP
Chargement des polices, de l'audio et des entites 
.PP
\fBParamètres\fP
.RS 4
\fItitle\fP chaine de caracteres 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void LibererRessources_Jeux (void)"

.PP
Fonction qui libere toutes les ressources du jeu\&. Destruction des structures rendu et fenetre 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Documentation des variables"
.PP 
.SS "SDL_Window* fenetre = NULL"
Structure de la fenetre 
.SS "SDL_Renderer* rendu = NULL"
Structure du rendu 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
