.TH "input" 3 "Vendredi 13 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "bool \fBleft\fP"
.br
.ti -1c
.RI "bool \fBright\fP"
.br
.ti -1c
.RI "bool \fBup\fP"
.br
.ti -1c
.RI "bool \fBdown\fP"
.br
.ti -1c
.RI "bool \fBjump\fP"
.br
.ti -1c
.RI "bool \fBattack\fP"
.br
.ti -1c
.RI "bool \fBenter\fP"
.br
.ti -1c
.RI "bool \fBerase\fP"
.br
.ti -1c
.RI "bool \fBpause\fP"
.br
.ti -1c
.RI "bool \fBescape\fP"
.br
.ti -1c
.RI "SDL_Event \fBevent\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
