.TH "src/input.c" 3 "Mercredi 25 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/input.c \- Programme qui gère les entrées de l'utilisateur en fonction de si l'utilisateur est en train de jouer ou bien sur le menu principal\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBProcessInput\fP (SDL_Event *event)"
.br
.RI "Fonction qui gere les entrees utilisateur\&. "
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère les entrées de l'utilisateur en fonction de si l'utilisateur est en train de jouer ou bien sur le menu principal\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "void ProcessInput (SDL_Event * event)"

.PP
Fonction qui gere les entrees utilisateur\&. Gestion des entrées utilisateurs\&.
.PP
En fonction de si l'utilisateur est en cours de partie, sur le menu principal, sur le menu pause, sur le menu game over ou si le niveau vient d'etre acheve 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP evenement (entree utilisateur) 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
