.TH "level" 3 "Mercredi 8 Avril 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
level
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <level\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBTexture_Manager\fP \fBlevelTextures\fP [5]"
.br
.ti -1c
.RI "\fBTexture_Manager\fP \fBlayer_1\fP"
.br
.ti -1c
.RI "\fBTexture_Manager\fP \fBlayer_2\fP"
.br
.ti -1c
.RI "\fBTexture_Manager\fP \fBlayer_3\fP"
.br
.ti -1c
.RI "int \fBdepartX\fP"
.br
.ti -1c
.RI "int \fBdepartY\fP"
.br
.ti -1c
.RI "int \fBcameraX\fP"
.br
.ti -1c
.RI "int \fBcameraY\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
structure gerant les niveux 
.SH "Documentation des champs"
.PP 
.SS "int cameraX"
le position x de la camera 
.SS "int cameraY"
la position y de la camera 
.SS "int departX"
Position de depart du joueur dans le niveau en X 
.SS "int departY"
Position de depart du joueur dans le niveau en Y 
.SS "\fBTexture_Manager\fP layer_1"
la couche 1 
.br
 
.SS "\fBTexture_Manager\fP layer_2"
la couche 2 
.br
 
.SS "\fBTexture_Manager\fP layer_3"
la couche 3 
.br
 
.SS "\fBTexture_Manager\fP levelTextures[5]"
levelTextures 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
