.TH "src/level.c" 3 "Vendredi 13 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/level.c \- Programme qui gère les niveaux : affichage et destruction des niveaux\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'level\&.h'\fP
.br
\fC#include 'constantes\&.h'\fP
.br
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBLevel\fP * \fBgetLevel\fP ()"
.br
.ti -1c
.RI "void \fBChargerNiveau\fP ()"
.br
.ti -1c
.RI "void \fBDebug_AfficherCollider\fP ()"
.br
.ti -1c
.RI "void \fBafficher_textures_niveau\fP (int niveau)"
.br
.ti -1c
.RI "void \fBAffichage_Niveau\fP ()"
.br
.ti -1c
.RI "void \fBDestructionNiveau\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBLevel\fP \fBlevel\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère les niveaux : affichage et destruction des niveaux\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
