.TH "src/main.c" 3 "Dimanche 17 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- Projet réalisé dans le cadre de la formation licence 2 informatiques de l'Université du Mans Le projet est un jeu de type plate-forme, réalisé en langage C avec l'appui de la librairie SDL2\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'basegame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "Programme principal du jeu\&. "
.in -1c
.SH "Description détaillée"
.PP 
Projet réalisé dans le cadre de la formation licence 2 informatiques de l'Université du Mans Le projet est un jeu de type plate-forme, réalisé en langage C avec l'appui de la librairie SDL2\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020
.RE
.PP
Programme principal du jeu 
.SH "Documentation des fonctions"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Programme principal du jeu\&. 
.PP
\fBParamètres\fP
.RS 4
\fIargc\fP nombre de paramètres 
.br
\fIargv\fP les arguments 
.RE
.PP
\fBRenvoie\fP
.RS 4
0 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
