.TH "src/main.c" 3 "Mercredi 5 Février 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- Jeux de plateforme 2D\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'commun\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Jeux de plateforme 2D\&. 

Projet réalisé dans le cadre de la formation licence 2 informatiques de l'Université du Mans Le projet est un jeu, réalisé en langage C avec l'appui de la librairie SDL2\&. 
.PP
\fBAuteur\fP
.RS 4
Calvados Cindy, Karina Ousmanovah, Cassandra Chaumullon, Celia Chelli 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
