.TH "src/menu_pause.c" 3 "Lundi 4 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/menu_pause.c \- Programme qui gère le menu de pause\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBGameObject\fP * \fBgetMenuPause\fP ()"
.br
.RI "Fonction qui permet retourner le menu de pause\&. "
.ti -1c
.RI "void \fBPause_Init\fP ()"
.br
.RI "Fonction qui initialise le menu de pause\&. "
.ti -1c
.RI "void \fBPause_Input\fP (SDL_Event *event)"
.br
.RI "Fonction qui gere les evenements du menu\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGameObject\fP \fBmenu_pause\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le menu de pause\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020
.RE
.PP
Initialisation, affichage du menu, navigation dans le menu, gestion des entrees clavier et destruction du menu 
.SH "Documentation des fonctions"
.PP 
.SS "\fBGameObject\fP * getMenuPause ()"

.PP
Fonction qui permet retourner le menu de pause\&. 
.PP
\fBRenvoie\fP
.RS 4
une structure menu de type GameObject 
.RE
.PP

.SS "void Pause_Init ()"

.PP
Fonction qui initialise le menu de pause\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Pause_Input (SDL_Event * event)"

.PP
Fonction qui gere les evenements du menu\&. Gestion des entrees clavier de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP evenement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Documentation des variables"
.PP 
.SS "\fBGameObject\fP menu_pause"
Structure de type GameObject 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
