.TH "src/menuPrincipal.c" 3 "Lundi 4 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/menuPrincipal.c \- Programme qui gère le menu principal\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBGameObject\fP * \fBgetGameObject\fP ()"
.br
.RI "Fonction qui permet retourner le menu principal\&. "
.ti -1c
.RI "int \fBgetTouchePresse\fP (\fBGameObject\fP *\fBgameObject\fP)"
.br
.RI "Fonction qui retourne l'option du menu selectionne\&. "
.ti -1c
.RI "void \fBInit_MenuPrincipal\fP ()"
.br
.RI "Fonction qui initialise le menu principal\&. "
.ti -1c
.RI "void \fBUpdateComponent\fP (\fBComponent\fP *\fBcomponent\fP, int etat)"
.br
.ti -1c
.RI "void \fBUpdateImage_Component\fP (\fBComponent\fP *\fBcomponent\fP, const char *filename)"
.br
.ti -1c
.RI "void \fBToucheHaut\fP (\fBGameObject\fP *\fBgameObject\fP)"
.br
.RI "Fonction qui permet de naviguer dans le menu vers le haut\&. "
.ti -1c
.RI "void \fBToucheBas\fP (\fBGameObject\fP *\fBgameObject\fP)"
.br
.RI "Fonction qui permet de naviguer dans le menu vers le bas\&. "
.ti -1c
.RI "void \fBDroite\fP (\fBGameObject\fP *\fBgameObject\fP, int nombresOptions)"
.br
.RI "Fonction qui permet de naviguer dans le menu a droite\&. "
.ti -1c
.RI "void \fBGauche\fP (\fBGameObject\fP *\fBgameObject\fP, int nombresOptions)"
.br
.RI "Fonction qui permet de naviguer dans le menu a gauche\&. "
.ti -1c
.RI "void \fBDessiner_Menu\fP (\fBGameObject\fP *\fBgameObject\fP, int nombresOptions, int posX, int posY, int largeurBG, int hauteurBG)"
.br
.RI "Fonction qui permet d'afficher le menu\&. "
.ti -1c
.RI "void \fBInput_MenuPrincipal\fP (SDL_Event *event)"
.br
.RI "Fonction qui gere les evenements du menu principal\&. "
.ti -1c
.RI "void \fBChargerData_Menu\fP (int numero, int num_image, \fBGameObject\fP *\fBgameObject\fP, char *nomOption, char *image_on, char *image_off, int positionX, int positionY)"
.br
.RI "Fonction qui gere le chargement des donnes du menu\&. "
.ti -1c
.RI "void \fBNettoyer_Menu\fP (\fBGameObject\fP *\fBgameObject\fP, int nombreOptions)"
.br
.RI "Fonction qui permet de nettoyer l'ecran du menu\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGameObject\fP \fB_gameObject\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le menu principal\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020
.RE
.PP
Initialisation, affichage du menu, navigation dans le menu, gestion des entrées clavier et destruction du menu 
.SH "Documentation des fonctions"
.PP 
.SS "void ChargerData_Menu (int numero, int num_image, \fBGameObject\fP * gameObject, char * nomOption, char * image_on, char * image_off, int positionX, int positionY)"

.PP
Fonction qui gere le chargement des donnes du menu\&. 
.PP
\fBParamètres\fP
.RS 4
\fInumero\fP numero de l'option 
.br
\fInum_image\fP numero de l'image selectionne par defaut 
.br
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fInomOption\fP nom de l'option 
.br
\fIimage_on\fP chemin pour acceder a l'image selectionnee 
.br
\fIimage_off\fP chemin pour acceder a l'image deselectionnee 
.br
\fIpositionX\fP position en x 
.br
\fIpositionY\fP position en y 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Dessiner_Menu (\fBGameObject\fP * gameObject, int nombresOptions, int posX, int posY, int largeurBG, int hauteurBG)"

.PP
Fonction qui permet d'afficher le menu\&. Affichage des différentes options 
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fInombresOptions\fP nombre d'options dans le menu 
.br
\fIposX\fP position en x de l'arriere plan 
.br
\fIposY\fP position en y de l'arriere plan 
.br
\fIlargeurBG\fP largeur de l'arriere plan 
.br
\fIhauteurBG\fP hauteur de l'arriere plan 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Droite (\fBGameObject\fP * gameObject, int nombresOptions)"

.PP
Fonction qui permet de naviguer dans le menu a droite\&. 
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fInombresOptions\fP nombre d'options 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Gauche (\fBGameObject\fP * gameObject, int nombresOptions)"

.PP
Fonction qui permet de naviguer dans le menu a gauche\&. 
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fInombresOptions\fP nombre d'options 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "\fBGameObject\fP * getGameObject ()"

.PP
Fonction qui permet retourner le menu principal\&. 
.PP
\fBRenvoie\fP
.RS 4
une structure menu de type GameObject 
.RE
.PP

.SS "int getTouchePresse (\fBGameObject\fP * gameObject)"

.PP
Fonction qui retourne l'option du menu selectionne\&. 
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.RE
.PP
\fBRenvoie\fP
.RS 4
un entier correspondant au numero de l'option selectionnee 
.RE
.PP

.SS "void Init_MenuPrincipal ()"

.PP
Fonction qui initialise le menu principal\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Input_MenuPrincipal (SDL_Event * event)"

.PP
Fonction qui gere les evenements du menu principal\&. Gestion des entrees clavier de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP evenement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Nettoyer_Menu (\fBGameObject\fP * gameObject, int nombreOptions)"

.PP
Fonction qui permet de nettoyer l'ecran du menu\&. 
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.br
\fInombreOptions\fP nombre d'options du menu 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void ToucheBas (\fBGameObject\fP * gameObject)"

.PP
Fonction qui permet de naviguer dans le menu vers le bas\&. 
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void ToucheHaut (\fBGameObject\fP * gameObject)"

.PP
Fonction qui permet de naviguer dans le menu vers le haut\&. 
.PP
\fBParamètres\fP
.RS 4
\fI\fBgameObject\fP\fP pointeur sur le menu 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void UpdateComponent (\fBComponent\fP * component, int etat)"
fonction de mise à jour du component d'un \fBgameObject\fP 
.SS "void UpdateImage_Component (\fBComponent\fP * component, const char * filename)"
fonction de mise à jour d'image du component d'un \fBgameObject\fP 
.SH "Documentation des variables"
.PP 
.SS "\fBGameObject\fP _gameObject"
Structure de type GameObject 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
