.TH "includes/menu_continue.h" 3 "Samedi 16 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/menu_continue.h \- programme qui gere le menu durant le jeu\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBContinue_Init\fP ()"
.br
.RI "Fonction qui initialise le menu 'continuer'\&. "
.ti -1c
.RI "void \fBContinue_Input\fP (SDL_Event *event)"
.br
.RI "Fonction qui gere les evenements du menu\&. "
.ti -1c
.RI "void \fBContinue_Load\fP ()"
.br
.RI "Fonction qui initialise l'etat continue\&. "
.in -1c
.SH "Description détaillée"
.PP 
programme qui gere le menu durant le jeu\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "void Continue_Init ()"

.PP
Fonction qui initialise le menu 'continuer'\&. l'initialisation du menu continue
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Continue_Input (SDL_Event * event)"

.PP
Fonction qui gere les evenements du menu\&. fonction input pour le menu continue
.PP
Gestion des entrees clavier de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP evenement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Continue_Load ()"

.PP
Fonction qui initialise l'etat continue\&. Fonction de chargement des ressources du menu continue
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
