.TH "includes/menu_win.h" 3 "Samedi 16 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/menu_win.h \- programme qui gere le menu de la partie gagnée  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBGameWin_Init\fP ()"
.br
.RI "Fonction qui initialise le menu du jeux gagné "
.ti -1c
.RI "void \fBGameWin_Input\fP (SDL_Event *event)"
.br
.RI "Fonction qui gere les evenements du menu\&. "
.in -1c
.SH "Description détaillée"
.PP 
programme qui gere le menu de la partie gagnée 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "void GameWin_Init ()"

.PP
Fonction qui initialise le menu du jeux gagné initialisation du menu de la partie gagnée 
.br
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void GameWin_Input (SDL_Event * event)"

.PP
Fonction qui gere les evenements du menu\&. gestion des entrées utilisateur du menu de la partie gagnée 
.br
.PP
Gestion des entrees clavier de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP evenement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
