.TH "src/menuPrincipal.c" 3 "Vendredi 6 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/menuPrincipal.c \- Programme qui gère le menu principal\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBMenu_t\fP * \fBgetMenu\fP ()"
.br
.ti -1c
.RI "int \fBgetTouchePresse\fP ()"
.br
.ti -1c
.RI "void \fBInit_MenuPrincipal\fP ()"
.br
.ti -1c
.RI "void \fBUpdateOption\fP (\fBOptions_t\fP *menut)"
.br
.ti -1c
.RI "void \fBToucheHaut\fP ()"
.br
.ti -1c
.RI "void \fBToucheBas\fP ()"
.br
.ti -1c
.RI "void \fBDessiner_MenuPrincipal\fP ()"
.br
.ti -1c
.RI "void \fBInput_MenuPrincipal\fP (SDL_Event *event)"
.br
.ti -1c
.RI "void \fBNettoyer_MenuPrincipal\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMenu_t\fP \fBmenu\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le menu principal\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020
.RE
.PP
Initialisation, affichage du menu, navigation dans le menu, gestion des entrées clavier et destruction du menu 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
