.TH "menu" 3 "Mercredi 8 Avril 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menuPrincipal\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBselectedOption\fP"
.br
.ti -1c
.RI "\fBOptions_t\fP \fBmenu\fP [4]"
.br
.ti -1c
.RI "Mix_Chunk * \fBson\fP"
.br
.ti -1c
.RI "TTF_Font * \fBpolice\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBbg\fP"
.br
.ti -1c
.RI "Mix_Music * \fBbgm\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure 
.SH "Documentation des champs"
.PP 
.SS "SDL_Texture* bg"
Texture en arrière-plan 
.SS "Mix_Music* bgm"
Musique du jeux en arriere plan 
.SS "\fBOptions_t\fP \fBmenu\fP[4]"
le menu 
.SS "TTF_Font* police"
la police utilise pour le menu 
.SS "int selectedOption"
selection de l'option 
.SS "Mix_Chunk* son"
le son du menu 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
