.TH "src/menuPrincipal.c" 3 "Samedi 21 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/menuPrincipal.c \- Programme qui gère le menu principal\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBMenu_t\fP * \fBgetMenu\fP ()"
.br
.ti -1c
.RI "int \fBgetTouchePresse\fP (\fBMenu_t\fP *\fBmenu\fP)"
.br
.ti -1c
.RI "void \fBInit_MenuPrincipal\fP ()"
.br
.ti -1c
.RI "void \fBUpdateOption\fP (\fBOptions_t\fP *menut, int etat)"
.br
.ti -1c
.RI "void \fBToucheHaut\fP (\fBMenu_t\fP *\fBmenu\fP)"
.br
.ti -1c
.RI "void \fBToucheBas\fP (\fBMenu_t\fP *\fBmenu\fP)"
.br
.ti -1c
.RI "void \fBDroite\fP (\fBMenu_t\fP *\fBmenu\fP)"
.br
.ti -1c
.RI "void \fBGauche\fP (\fBMenu_t\fP *\fBmenu\fP)"
.br
.ti -1c
.RI "void \fBDessiner_Menu\fP (\fBMenu_t\fP *\fBmenu\fP, int nombresOptions, int posX, int posY, int largeurBG, int hauteurBG)"
.br
.ti -1c
.RI "void \fBInput_MenuPrincipal\fP (SDL_Event *event)"
.br
.ti -1c
.RI "void \fBChargerData_Menu\fP (int numero, int num_image, \fBMenu_t\fP *\fBmenu\fP, char *nomOption, char *image_on, char *image_off, int positionX, int positionY)"
.br
.ti -1c
.RI "void \fBNettoyer_Menu\fP (\fBMenu_t\fP *\fBmenu\fP, int nombreOptions)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMenu_t\fP \fBmenu\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le menu principal\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020
.RE
.PP
Initialisation, affichage du menu, navigation dans le menu, gestion des entrées clavier et destruction du menu 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
