.TH "src/menu_help.c" 3 "Mardi 19 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/menu_help.c \- Programme qui gère le menu d'aide\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'basegame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBGameObject\fP * \fBgetHelp\fP ()"
.br
.ti -1c
.RI "void \fBHelp_Init\fP ()"
.br
.RI "Fonction qui initialise l'affichage de l'aide\&. "
.ti -1c
.RI "void \fBHelp_Input\fP (SDL_Event *event)"
.br
.RI "Fonction qui gere les evenements de l'aide\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGameObject\fP \fBhelp\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le menu d'aide\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mai 2020
.RE
.PP
Initialisation, affichage du menu, navigation dans le menu, gestion des entrees clavier et destruction du menu 
.SH "Documentation des fonctions"
.PP 
.SS "void Help_Init ()"

.PP
Fonction qui initialise l'affichage de l'aide\&. 
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Help_Input (SDL_Event * event)"

.PP
Fonction qui gere les evenements de l'aide\&. Gestion des entrees clavier de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP evenement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Documentation des variables"
.PP 
.SS "\fBGameObject\fP help"
Structure de type GameObject 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
