.TH "includes/menuLoad.h" 3 "Dimanche 5 Avril 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/menuLoad.h \- programme qui gere le menu de chargemnt du jeu\&.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBInit_MenuLoad\fP ()"
.br
.RI "Fonction qui initialise le menu de chargement\&. "
.ti -1c
.RI "void \fBInput_MenuLoad\fP (SDL_Event *event)"
.br
.RI "Fonction qui gere les evenements du menu\&. "
.ti -1c
.RI "void \fBInit_Pause\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
programme qui gere le menu de chargemnt du jeu\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "void Init_MenuLoad ()"

.PP
Fonction qui initialise le menu de chargement\&. fonction d'initialisation du menu de chargemet
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Init_Pause ()"
fonction d'initialisation du fichiers pause 
.SS "void Input_MenuLoad (SDL_Event * event)"

.PP
Fonction qui gere les evenements du menu\&. input du menu
.PP
Gestion des entrees clavier de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP evenement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
