.TH "includes/menu_principal.h" 3 "Dimanche 17 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/menu_principal.h \- programme qui gere le menu pricipal du jeu\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_MENU_PRINCIPAL_H\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBPrincipal_Init\fP ()"
.br
.RI "Fonction qui initialise le menu principal\&. "
.ti -1c
.RI "void \fBPrincipal_Input\fP (SDL_Event *event)"
.br
.RI "Fonction qui gere les evenements du menu principal\&. "
.in -1c
.SH "Description détaillée"
.PP 
programme qui gere le menu pricipal du jeu\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
mars 2020 
.RE
.PP

.SH "Documentation des macros"
.PP 
.SS "#define _MENU_PRINCIPAL_H"
< 
.SH "Documentation des fonctions"
.PP 
.SS "void Principal_Init ()"

.PP
Fonction qui initialise le menu principal\&. initialisation du menu principal
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void Principal_Input (SDL_Event * event)"

.PP
Fonction qui gere les evenements du menu principal\&. gestion des entrées utilisateur du menu principal
.PP
Gestion des entrees clavier de l'utilisateur 
.PP
\fBParamètres\fP
.RS 4
\fIevent\fP evenement 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
