.TH "Node" 3 "Samedi 2 Mai 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <listeElements\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBvx\fP"
.br
.ti -1c
.RI "float \fBvy\fP"
.br
.ti -1c
.RI "\fBtypeEntite\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBestMort\fP"
.br
.ti -1c
.RI "int \fBnb_lancer\fP"
.br
.ti -1c
.RI "SDL_Rect * \fBrect\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBactif\fP"
.br
.ti -1c
.RI "int \fBnb_objets\fP"
.br
.ti -1c
.RI "float \fBbaseX\fP"
.br
.ti -1c
.RI "float \fBbaseY\fP"
.br
.ti -1c
.RI "float \fBphase\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBlancer\fP"
.br
.ti -1c
.RI "float \fBmovingX\fP"
.br
.ti -1c
.RI "\fBTexture_Manager\fP \fBimagesItem\fP [2]"
.br
.ti -1c
.RI "int \fBimageCourante\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBsuivant\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
structure gerant les noeud de la liste 
.SH "Documentation des champs"
.PP 
.SS "\fBbool\fP actif"
Défini si l'élement est actif ou non> 
.SS "float baseX"
Position de départ en X 
.SS "float baseY"
Position de départ en Y 
.SS "\fBbool\fP estMort"
un type booleen pour savoir c'est l'entite est mort> 
.SS "float h"
hauteur de l'entite 
.SS "int imageCourante"
Determine l'image actuellement visible a l'écran 
.SS "\fBTexture_Manager\fP imagesItem[2]"
Tableau de texture pour un element 
.SS "\fBbool\fP lancer"
float des lancer 
.SS "float movingX"
les deplacements selon x 
.SS "int nb_lancer"
un compteur pour savoir le nb de lancer, attaque en cours> 
.SS "int nb_objets"
le nombres d'objets 
.SS "float phase"
float de la phase 
.SS "SDL_Rect* rect"
Rectangle qui défini la taille d'un éléments> 
.SS "struct \fBNode\fP* suivant"
Pointeur vers l'element suivant 
.SS "\fBtypeEntite\fP type"
le type de l'entite 
.SS "float vx"
la velocite x la vitesse laquelle va l'entite dans une direction x 
.SS "float vy"
la velocite y , la vitesse laquelle va l'entite dans une direction y 
.SS "float w"
largeur de l'entite 
.SS "float x"
la position x 
.SS "float y"
la position y 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
