.TH "Node" 3 "Mercredi 25 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "SDL_Rect * \fBrect\fP"
.br
.ti -1c
.RI "bool \fBactif\fP"
.br
.ti -1c
.RI "int \fBnb_objets\fP"
.br
.ti -1c
.RI "float \fBbaseX\fP"
.br
.ti -1c
.RI "float \fBbaseY\fP"
.br
.ti -1c
.RI "float \fBphase\fP"
.br
.ti -1c
.RI "bool \fBlancer\fP"
.br
.ti -1c
.RI "float \fBmovingX\fP"
.br
.ti -1c
.RI "\fBTexture_Manager\fP \fBimagesItem\fP [2]"
.br
.ti -1c
.RI "int \fBimageCourante\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBsuivant\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
