.TH "Node" 3 "Lundi 4 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node \- structure gerant les noeud de la liste  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <listeElements\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "SDL_Rect * \fBrect\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBactif\fP"
.br
.ti -1c
.RI "int \fBnb_objets\fP"
.br
.ti -1c
.RI "float \fBbaseX\fP"
.br
.ti -1c
.RI "float \fBbaseY\fP"
.br
.ti -1c
.RI "float \fBphase\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBlancer\fP"
.br
.ti -1c
.RI "float \fBmovingX\fP"
.br
.ti -1c
.RI "\fBTexture_Manager\fP \fBimagesItem\fP [2]"
.br
.ti -1c
.RI "int \fBimageCourante\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
structure gerant les noeud de la liste 
.SH "Documentation des champs"
.PP 
.SS "\fBbool\fP actif"
Défini si l'élement est actif ou non> 
.SS "float baseX"
Position de départ en X 
.SS "float baseY"
Position de départ en Y 
.SS "int imageCourante"
Determine l'image actuellement visible a l'écran 
.SS "\fBTexture_Manager\fP imagesItem[2]"
Tableau de texture pour un element 
.SS "\fBbool\fP lancer"
float des lancer 
.SS "float movingX"
les deplacements selon x 
.SS "int nb_objets"
le nombres d'objets 
.SS "struct \fBNode\fP* next"
Pointeur vers l'element suiv 
.SS "float phase"
float de la phase 
.SS "SDL_Rect* rect"
Rectangle qui défini la taille d'un éléments> 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
