.TH "option" 3 "Mercredi 25 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
option
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menuPrincipal\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBlargeur\fP"
.br
.ti -1c
.RI "int \fBhauteur\fP"
.br
.ti -1c
.RI "const char * \fBnomOption\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBtexture\fP"
.br
.ti -1c
.RI "SDL_Color \fBcouleur\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP [4]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure gérant les caractéristiques liées à une option 
.SH "Documentation des champs"
.PP 
.SS "SDL_Color couleur"
couleur de l'option 
.SS "char* filename[4]"
nom du fichier pour la texture de l'option 
.SS "int hauteur"
largeur et hauteur de l'option 
.SS "const char* nomOption"
nom de l'option 
.SS "SDL_Texture* texture"
texture de l'option 
.SS "int y"
position en x et en y de l'option 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
