.TH "player" 3 "Mercredi 25 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
player
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBvx\fP"
.br
.ti -1c
.RI "float \fBvy\fP"
.br
.ti -1c
.RI "typeEntite \fBtype\fP"
.br
.ti -1c
.RI "bool \fBestMort\fP"
.br
.ti -1c
.RI "int \fBnb_lancer\fP"
.br
.ti -1c
.RI "int \fBm_frameWidth\fP"
.br
.ti -1c
.RI "int \fBm_frameHeight\fP"
.br
.ti -1c
.RI "int \fBm_textureWidth\fP"
.br
.ti -1c
.RI "int \fBm_textureHeight\fP"
.br
.ti -1c
.RI "float \fBposXDepart\fP"
.br
.ti -1c
.RI "float \fBposYDepart\fP"
.br
.ti -1c
.RI "float \fBnumeroImage\fP"
.br
.ti -1c
.RI "SDL_Rect \fBplayerRect\fP"
.br
.ti -1c
.RI "SDL_Rect \fBplayerPosition\fP"
.br
.ti -1c
.RI "int \fBoriginX\fP"
.br
.ti -1c
.RI "int \fBoriginY\fP"
.br
.ti -1c
.RI "float \fBanimationSpeed\fP"
.br
.ti -1c
.RI "int \fBframe\fP"
.br
.ti -1c
.RI "bool \fBestActif\fP"
.br
.ti -1c
.RI "bool \fBestTourne\fP"
.br
.ti -1c
.RI "bool \fBestSurSol\fP"
.br
.ti -1c
.RI "int \fBnombreVies\fP"
.br
.ti -1c
.RI "bool \fBralenti\fP"
.br
.ti -1c
.RI "float \fBscrollX\fP"
.br
.ti -1c
.RI "int \fBniveau\fP"
.br
.ti -1c
.RI "int \fBnb_objet\fP"
.br
.ti -1c
.RI "\fBTexture_Manager\fP \fBtex\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "bool estMort"
<le type de l'entite> 
.SS "int m_frameWidth"
<un compteur pour savoir le nb de lancer, attaque en cours> Données pour l'animation 
.SS "int nb_lancer"
<un type booleen pour savoir c'est l'entite est mort> 
.SS "typeEntite type"
<la velocite x et velocite y, la vitesse laquelle va l'entite dans une direction> 
.SS "float vx"
<la position x et y> 
.SS "float x"
<largeur et hauteur de l'entite> 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
