.TH "player" 3 "Dimanche 29 Mars 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
player
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <player\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBvx\fP"
.br
.ti -1c
.RI "float \fBvy\fP"
.br
.ti -1c
.RI "\fBtypeEntite\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBestMort\fP"
.br
.ti -1c
.RI "int \fBnb_lancer\fP"
.br
.ti -1c
.RI "int \fBm_frameWidth\fP"
.br
.ti -1c
.RI "int \fBm_frameHeight\fP"
.br
.ti -1c
.RI "int \fBm_textureWidth\fP"
.br
.ti -1c
.RI "int \fBm_textureHeight\fP"
.br
.ti -1c
.RI "float \fBposXDepart\fP"
.br
.ti -1c
.RI "float \fBposYDepart\fP"
.br
.ti -1c
.RI "float \fBnumeroImage\fP"
.br
.ti -1c
.RI "SDL_Rect \fBplayerRect\fP"
.br
.ti -1c
.RI "SDL_Rect \fBplayerPosition\fP"
.br
.ti -1c
.RI "int \fBoriginX\fP"
.br
.ti -1c
.RI "int \fBoriginY\fP"
.br
.ti -1c
.RI "float \fBanimationSpeed\fP"
.br
.ti -1c
.RI "int \fBframe\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBestActif\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBestTourne\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBestSurSol\fP"
.br
.ti -1c
.RI "int \fBnombreVies\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBralenti\fP"
.br
.ti -1c
.RI "int \fBniveau\fP"
.br
.ti -1c
.RI "int \fBnb_objet\fP"
.br
.ti -1c
.RI "\fBTexture_Manager\fP \fBtex\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure gérant les caractéristiques liées au joueur 
.SH "Documentation des champs"
.PP 
.SS "float animationSpeed"
Vitesse de l'animation 
.SS "\fBbool\fP estActif"
le booleen est actif 
.SS "\fBbool\fP estMort"
un type booleen pour savoir c'est l'entite est mort> 
.SS "\fBbool\fP estSurSol"
le booleen est sur le sol 
.SS "\fBbool\fP estTourne"
le booleen est tourne 
.SS "int frame"
le cadre 
.SS "float h"
hauteur de l'entite 
.SS "int m_frameHeight"
la hauteur de l'image a afficher 
.SS "int m_frameWidth"
Données pour l'animation la largueur de l'image a afficher 
.SS "int m_textureHeight"
hauteur de la texture 
.SS "int m_textureWidth"
largueur de la texture 
.SS "int nb_lancer"
un compteur pour savoir le nb de lancer, attaque en cours> 
.SS "int nb_objet"
nombres d'objets qui a le joueur 
.SS "int niveau"
le niveau du joueur 
.SS "int nombreVies"
le nombre de vie du joueur 
.SS "float numeroImage"
le numero de l'image 
.SS "int originX"
Origine du personnage en X 
.SS "int originY"
Origine du personnage en Y 
.SS "SDL_Rect playerPosition"
la position du joueur 
.SS "SDL_Rect playerRect"
la position du joueur 
.SS "float posXDepart"
sa positon de depart selon x 
.SS "float posYDepart"
sa positon de depart selon y 
.SS "\fBbool\fP ralenti"
le ralentisement du joueur 
.SS "\fBTexture_Manager\fP tex"
Texture du joueur 
.SS "\fBtypeEntite\fP type"
le type de l'entite 
.SS "float vx"
la velocite x la vitesse laquelle va l'entite dans une direction x 
.SS "float vy"
la velocite y , la vitesse laquelle va l'entite dans une direction y 
.SS "float w"
largeur de l'entite 
.SS "float x"
la position x 
.SS "float y"
la position y 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
