.TH "src/scores.c" 3 "Jeudi 2 Avril 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/scores.c \- Programme qui gère le score\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBHUD\fP * \fBgetScores\fP ()"
.br
.RI "Retourne l'instance de l'objet score\&. "
.ti -1c
.RI "\fBHUD\fP * \fBgetNiveau\fP ()"
.br
.RI "Retourne l'instance de l'objet niveau\&. "
.ti -1c
.RI "\fBHUD\fP * \fBgetTime\fP ()"
.br
.RI "Retourne l'instance de l'objet niveau\&. "
.ti -1c
.RI "\fBHUD\fP * \fBgetItem\fP (int num_item)"
.br
.RI "Retourne de l'item séléction\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBHUD\fP \fBscore\fP"
.br
.ti -1c
.RI "\fBHUD\fP \fBniveau\fP"
.br
.ti -1c
.RI "\fBHUD\fP \fBitem_s\fP [3]"
.br
.ti -1c
.RI "\fBHUD\fP \fBtime_\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère le score\&. 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020
.RE
.PP
Initialisation, mise à jour, affichage et destruction du score 
.SH "Documentation des fonctions"
.PP 
.SS "\fBHUD\fP * getItem (int num_item)"

.PP
Retourne de l'item séléction\&. 
.PP
\fBParamètres\fP
.RS 4
\fInum_item\fP correspond au numéro de l'item selectionné
.RE
.PP
Cela permet d'instaurer un contexte privé 
.PP
\fBRenvoie\fP
.RS 4
Retourne un pointeur sur l'objet séléctionné 
.RE
.PP

.SS "\fBHUD\fP * getNiveau ()"

.PP
Retourne l'instance de l'objet niveau\&. Cela permet d'instaurer un contexte privé 
.PP
\fBRenvoie\fP
.RS 4
Retourne un pointeur sur l'objet niveau 
.RE
.PP

.SS "\fBHUD\fP * getScores ()"

.PP
Retourne l'instance de l'objet score\&. Cela permet d'instaurer un contexte privé 
.PP
\fBRenvoie\fP
.RS 4
Retourne un pointeur sur l'objet score 
.RE
.PP

.SS "\fBHUD\fP * getTime ()"

.PP
Retourne l'instance de l'objet niveau\&. Cela permet d'instaurer un contexte privé 
.PP
\fBRenvoie\fP
.RS 4
Retourne un pointeur sur l'objet niveau 
.RE
.PP

.SH "Documentation des variables"
.PP 
.SS "\fBHUD\fP item_s[3]"
hud des items du jeux 
.SS "\fBHUD\fP niveau"
hud du niveau 
.SS "\fBHUD\fP score"
hud du score 
.SS "\fBHUD\fP time_"
hud du timer 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
