.TH "textures" 3 "Samedi 16 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textures \- Structure gérant les textures 
.PP
.RS 4

.PP
.RS 4

.PP
.RS 4

.PP
.RS 4

.PP
.RS 4

.PP
.RS 4

.PP
.RS 4
674e9288e4b728278a91af8e9aad7255f9ee44f2 
.RE
.PP
.RE
.PP
.RE
.PP
.RE
.PP
.RE
.PP
.RE
.PP
.RE
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <texture\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBtexture\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure gérant les textures 
.PP
.RS 4

.PP
.RS 4

.PP
.RS 4

.PP
.RS 4

.PP
.RS 4

.PP
.RS 4

.PP
.RS 4
674e9288e4b728278a91af8e9aad7255f9ee44f2 
.RE
.PP
.RE
.PP
.RE
.PP
.RE
.PP
.RE
.PP
.RE
.PP
.RE
.PP


structure des differentes textures du jeu 
.SH "Documentation des champs"
.PP 
.SS "int h"
hauteur de la texture 
.SS "SDL_Texture* texture"
texture 
.SS "int w"
largeur de la texture 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
