.TH "textures" 3 "Lundi 4 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textures
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <texture\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBtexture\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
structure des differentes textures du jeu
.PP
les structures du fichier commun\&.h
.PP
Structure gérant les textures 
.SH "Documentation des champs"
.PP 
.SS "int h"
hauteur de la texture 
.SS "SDL_Texture* texture"
texture 
.SS "int w"
largeur de la texture 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
