.TH "Texture_Manager" 3 "Samedi 16 Mai 2020" "Version 0.2" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Texture_Manager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <texture\&.h>\fP
.SH "Description détaillée"
.PP 
les structures du fichier commun\&.h <<<<<<< HEAD
.SH "\\details Structure gérant les textures"
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
