.TH "src/texture.c" 3 "Dimanche 3 Mai 2020" "Version 0.1" "Beauty Savior" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/texture.c \- Programme qui gère les textures (affichage)  

.SH SYNOPSIS
.br
.PP
\fC#include 'texture\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBchargerImage\fP (\fBTexture_Manager\fP *tex, const char *filename)"
.br
.RI "Fonction qui permet de charger une image dans une texture\&. "
.ti -1c
.RI "void \fBChargerTextureManager\fP (\fBTexture_Manager\fP *tex, char *filepath)"
.br
.RI "Fonction qui permet de charger une texture\&. "
.ti -1c
.RI "SDL_Texture * \fBChargerTexture\fP (char *filepath)"
.br
.RI "Fonction qui permet de charger une texture a partir d'une image\&. "
.ti -1c
.RI "void \fBLibererRessources\fP (\fBTexture_Manager\fP *tex)"
.br
.RI "Fonction qui permet detruire une texture\&. "
.in -1c
.SH "Description détaillée"
.PP 
Programme qui gère les textures (affichage) 


.PP
\fBAuteur\fP
.RS 4
CALVADOS Cindy, CHAUMULON Cassandra, CHELLI Célia, OUSMANOVA Karina 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
janvier 2020
.RE
.PP
Chargement des images, des textures, des textes et destruction des textures 
.SH "Documentation des fonctions"
.PP 
.SS "\fBbool\fP chargerImage (\fBTexture_Manager\fP * tex, const char * filename)"

.PP
Fonction qui permet de charger une image dans une texture\&. 
.PP
\fBParamètres\fP
.RS 4
\fItex\fP pointeur sur la texture dans laquelle on veut charger l'image 
.br
\fIfilename\fP nom du fichier de l'image 
.RE
.PP
\fBRenvoie\fP
.RS 4
un booleen : VRAI si l'image a bien ete chargee dans la texture, FAUX sinon
.RE
.PP
chargements des images 
.SS "SDL_Texture * ChargerTexture (char * filepath)"

.PP
Fonction qui permet de charger une texture a partir d'une image\&. 
.PP
\fBParamètres\fP
.RS 4
\fIfilepath\fP chemin pour acceder a l'image 
.RE
.PP
\fBRenvoie\fP
.RS 4
un pointeur sur une texture SDL (SDL_Texture)
.RE
.PP
chargement des textures 
.SS "void ChargerTextureManager (\fBTexture_Manager\fP * tex, char * filepath)"

.PP
Fonction qui permet de charger une texture\&. 
.PP
\fBParamètres\fP
.RS 4
\fItex\fP pointeur sur la texture dans laquelle on veut charger l'image 
.br
\fIfilepath\fP nom du fichier de l'image 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void) 
.RE
.PP

.SS "void LibererRessources (\fBTexture_Manager\fP * tex)"

.PP
Fonction qui permet detruire une texture\&. 
.PP
\fBParamètres\fP
.RS 4
\fItex\fP pointeur sur la texture a detruire 
.RE
.PP
\fBRenvoie\fP
.RS 4
pas de valeur de retour (void)
.RE
.PP
les ressources 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Beauty Savior à partir du code source\&.
